### PR TITLE
Update README.md (thumbnails-check)

### PR DESCRIPTION
**Pull request by lasers**
@RobLoach Does this work for you?

### CODE REVIEW

**Comment by RobLoach** [comment]
Maybe just a link to it as number 4 of "Thumbnail submission guidelines"?

**Comment by lasers** [comment]
I can't edit without making another commit here. Your call.

**Comment by RobLoach** [comment]
Another commit is no problem, we can Squash it all during the merge :wink: #gitwin

**Comment by RobLoach** [comment]
Looks good! :+1:

**Pull request merged**
