### PR TITLE
proposal and initial image set for FB Alpha Boxart

### PR DESCRIPTION
**Pull request by markwkidd**
I would like to put forward a set of images I gathered and formatted as "boxart" thumbnails for FB Alpha arcade ROMs.

**FB Alpha - Arcade Games/Named_Boxarts/: https://drive.google.com/drive/folders/0B4gWQ8g8Bzq3LTZRSDJmTm5RQ1E**

I think being able to see the cabinet or at least a bit of the artwork -- this is one of my favorite ways to browse through the FB Alpha game list. The images were matched in this priority order: cabinet image > marquee art > decal. If no art is available from that database in any of these categories, there will not be an image for that ROM in this set yet.

The images in this collection were gathered by using the ADB tool to match a complete set of FB Alpha 0.2.97.38 arcade ROMs with arcade database at http://adb.arcadeitalia.net/. The resulting images were sized at 512px wide and renamed based on the game titles in the XML DAT.

### CODE REVIEW

**Comment by markwkidd** [comment]
@Kivutar I know that you put together the existing thumbails for FB Alpha -- is there any chance you could take a look this concept for 'boxart'? 

Google drive link: https://drive.google.com/drive/folders/0B4gWQ8g8Bzq3LTZRSDJmTm5RQ1E

**Comment by Kivutar** [comment]
@markwkidd I took a look at it. And I think the set is too far from what we call boxarts. Arcade games have what we call flyers https://www.google.fr/search?q=arcade+flyers&safe=off&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwipqfrMvu7NAhXKaRQKHfEBAVYQ_AUICSgC&biw=1440&bih=765

And I would prefer to have flyers here.

**Comment by markwkidd** [comment]
Oh no - I tried flyers first but I thought they were ugly compared to the arcade cabinets! 8)

But I can produce a collection with flyers instead soon if you're dead set on them instead of cabinets.

**Comment by Kivutar** [comment]
I think they are more beautiful and the feat better because their is a common language between them, and they are graphical, while the cabinet set is partly photographical.

**Comment by markwkidd** [comment]
I grabbed a set of matching flyer images from adb.arcadeitalia.net and ran them through the resizing and renaming process. The set is almost finished synchronizing and has a total of 1,903 images.

Here's a link to the Google share: https://drive.google.com/open?id=0B4gWQ8g8Bzq3R2NqRmNxMXotenc

I'm also attaching the [unmatched.txt](https://github.com/libretro/libretro-thumbnails/files/363050/unmatched.txt) that the AuthoHotKey script produces in case it is useful. It lists ROMs that don't have flyers, both their standard MAME file name and by the DAT/RetroArch playlist name.

**Comment by Kivutar** [comment]
Thanks a lot. Very nice work, they look perfect. Should I wait until the set is finished?

**Comment by markwkidd** [comment]
Great! Everything looks like it's done uploading on this end now -- there should be 1,903 images in the folder. If so, this should be ready.

**Comment by markwkidd** [comment]
I adapted the same process for use to create a set of thumbnails for MAME 2003 / 0.78 as well: https://github.com/libretro/libretro-thumbnails/pull/80

**Comment by markwkidd** [comment]
@Axiphel I saw your comment in the current PSX pull request about the process for how to submit. I get the feeling that this request and the MAME 2003 thumbnails (here: https://github.com/libretro/libretro-thumbnails/pull/80) aren't arriving to you all in exactly the way you prefer.

I'm not especially familiar with github but I'm willing to learn. Is the proper way for me to submit these that I fork the repository locally, add the images, and then upload/sync? What do you recommend?

**Comment by RobLoach** [comment]
Thanks for putting these together, @markwkidd! Merged over at https://github.com/libretro/libretro-thumbnails/issues/93 . Could likely close this issue now that it's in. :+1:

**Comment by markwkidd** [comment]
Thanks!  and agreed about closing.

**Pull request closed without merging**
