### PR TITLE
Few PSX images added

### PR DESCRIPTION
**Pull request by davmanypsp**

### CODE REVIEW

**Comment by twinaphex** [comment]
Can you fix this PR?

**Comment by davmanypsp** [comment]
Sorry, How do I do that?

**Comment by Axiphel** [comment]
I don't know much about github but I think it's because of Destruction Derby Raw (Europe) (En,Fr,De,Es,It).png since there is already one of those in the master and your pull request is adding it instead of 'changing' it so github doesn't know which file to use. Your fork is nearly 400 commits out of date so there's bound to be some inconsistencies cropping up.

**Comment by davmanypsp** [comment]
I’m a total noob with Github, Could you explain me how do I update my fork? I’m using the web version. Or sould I just delete my fork and create a new one?

**Comment by Axiphel** [comment]
Shit I just delete mine and fork it again.

**Pull request closed without merging**
