### PR TITLE
scrub prohibited characters from thumb filenames

### PR DESCRIPTION
**Pull request by markwkidd**
My exploration of the thumbnail repository while trying to figure out why I couldn't clone it to my Windows PC turned up thousands of filenames with characters that are prohibited by the RetroArch cross-platform file-naming scheme.

I therefore cloned the repository to an OS X host and created a simple script using the linux 'rename' command to handle the bulk of the corrections. There is also a bit of hand-correction represented in the PR.

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi, do the entries still match with the entries in the databases though as part of this change?

**Comment by markwkidd** [comment]
That is a good question. 

If the playlist database has transformed these characters into underscores, this PR would mean that a bunch of thumbnails have just started matching their corresponding database entries.

From what I have been watching in this repo and libretro-database, that scenario is *possible* but not guaranteed. @RobLoach may know the answer immediately due to his involvement in the db.

On the other hand, if you could point me towards the right file in the database repo, I could spot check some of these entries myself and see if this change will need to be mirrored on the database side.

**Comment by RobLoach** [comment]
Just tested with `Bill _ Ted's Excellent Adventure (USA, Europe).png`, and it doesn't match....

screenshot at 2016-11-13 14-07-31

Not quite sure where the filenames are "cleansed", but I did find:
https://github.com/libretro/RetroArch/blob/444d95797878882690608f16d4e672b49292bbfd/menu/drivers/xmb.c#L714

Not seeing it replace an `&` anywhere. Know where that would happen?

**Comment by markwkidd** [comment]
When I see that the automatically generated playlist you have in your screenshot includes a & in the game title, am I right in inferring that the intended behavior in RetroArch is something like this?

Playlist generation:
1) Use hash values to match ROM files to known-good databases such as No-Intro.
2) Create playlist using 'display names' from the known-good databases

Playlist display:
1) Read display name from the playlist file
2) Transform characters that are not cross-platform friendly into underscores in a variable
3) Look for a thumbnail file that matches this "sanitized" name
4) Display the thumbnail image

**Comment by markwkidd** [comment]
Here is the list of characters I have been referring to as needing to be transformed to underscores for thumbnail filenames due to one or more common filesystem not supporting the character `& \ / ? : < > : * |`

I could swear that I originally took this list down from a post by @Kivutar, either on github or in the forums, but I can't find this post. Maybe it was a conversation in IRC but I don't keep IRC logs. Or I'm mis-attributing the list of characters and that's what I can't find the source.

**Comment by markwkidd** [comment]
Hey @RobLoach -- With assistance, I have committed a branch to libretro/RetroArch that should make the Bill & Ted's Excellent Adventure (USA, Europe) thumbnail appear. Here's the PR: https://github.com/libretro/RetroArch/pull/3996

**Comment by markwkidd** [comment]
I know that this PR touches a lot of files, so I wouldn't mind anyone kicking the tires.

I'm pasting in below the OS X bash script that I used to bulk rename for this PR so you can get an idea of the methodology.

**sanitizer.sh -- meant to be executed in the root libetro-thumbnails repo folder**
```
#!/bin/bash

function sanitize_characters {
	rename -fS "&apos;" "'" *
	rename -fS "&amp;" '_' *
	rename -fS "&" "_" *
	rename -fS "\\" "_" *
	rename -fS "/" "_" *
	rename -fS "?" "_" *
	rename -fS ":" "_" *
	rename -fS "\\\`" "_" *
	rename -fS "<" "_" *
	rename -fS ">" "_" *
	rename -fS "*" "_" *
	rename -fS "|" "_" *
}

for first_level in */ ; do
  if [[ -d "$first_level" && ! -L "$first_level" ]]; then
    cd "$first_level"
    echo $first_level
    for second_level in */ ; do
    	cd "$second_level"
    	echo $second_level
    	sanitize_characters $second_level
    	cd ..
    done
	cd ..
fi;
done

exit```

**Comment by markwkidd** [comment]
@twinaphex I think this is ready to commit. To answer your question from a few days back: another commit in libretro/RetroArch earlier today addresses potential disagreements between the playlist database and the thumbnail files that arise as a result of this PR ( https://github.com/libretro/RetroArch/commit/5be99842b5f664ed1274c0b6918712bdac4241c5 ) 

The net effect of the two changes should be better cross-platform thumbnail support as well as the possibility of displaying 'prohibited' characters in playlists while still looking for the properly sanitized thumbnail filename.

Existing playlists will continue to work in scenarios where a user updates RetroArch but keeps their playlists and downloaded thumbnail packs from before this change.

**Comment by RobLoach** [comment]
Here's the cross-posted screenshot I took with the filxed...
```
Bill _ Ted's Excellent Adventure (USA, Europe).png
```

**Pull request merged**
