### PR TITLE
MAME 'omnibus' thumbnail addition

### PR DESCRIPTION
**Pull request by markwkidd**
This thumbnail set began with the arcadeitalia's thumbnails for MAME 0.159 (MAME 2014 core). Then I added support for name variations needed by Progetto-SNAPS datfiles for the historical MAME cores (MAME 2000, 2003, 2010). This resulting 'omnibus' MAME thumbnail set is only a 7% increase in total archive size from thumbs for MAME 2014 alone.

Thumbnails that started as less than 512px wide remain at their original resolution for RetroArch to scale up. Thumbnails that were larger than 512px wide are scaled down to 512px.

**The first two commits associated with the mame-thumbnail-integration complete the Named_Titles folder.** It has been difficult to get these thumbs synced with github, probably due to either my unfamiliarity with git, lack of access to good broadband here, or because these thumbnail sets are pushing github to its limits with the file counts.

I'm still working to push the Named_Snaps and Named_Boxarts folders, but that may take another few days or a week to complete while I work through the connection errors. Assuming that goes well, I do intend to push the Titles and Boxart to this same branch. In the meantime, those thumbs are also available via mega.nz if it is useful:

- Named_Boxarts: https://mega.nz/#!0hMjQBzD!b2xztJUmz0KxTRvs8ZLR-BhjdVOWMe0TeM4OzjpKQtM
- Named_Snaps (v2) https://mega.nz/#!YxkAyCqK!43wNbAzCcSd3dTOYdGk6imKagXWLvjCoHLH9KfmJi58
- Named_Titles (v2) https://mega.nz/#!FxkikLxJ!n32J6V8UIZtyVw93ypytEpuDo_SLADEiukgGMitQzuI

### CODE REVIEW

**Comment by kwyxz** [comment]
Hello,

Just to let you know, if you used the names provided by running mame -listfull to name your thumbnails, there is a bunch of characters that need to be replaced. For example, `~` `&` `/` are causing problems with several filesystems and possibly GitHub. 

The convention for renaming seems to be using _ instead of these problematic characters : I have been running into a similar issue with [my own pull request](https://github.com/libretro/libretro-thumbnails/pull/141)

Hope this helps!

**Comment by markwkidd** [comment]
Hi @kwyxz. Thanks for your note! I've been very careful to sanitize the filenames, but I'm willing to believe I missed a few.

Do you have an example of a filename that my rename script missed? That would help me zero in on the issue.

**Comment by kwyxz** [comment]
Hi @markwkidd, I saw after posting my comment that you were very much aware of the sanitizing issue and already spoke about it in other bug reports. It's hard for me to say if you really missed an illegal character. Are you pushing your commits through git or using github's interface to do so?

**Comment by markwkidd** [comment]
I am using a git client, just because the github web interface has trouble with large file uploads.

Right now I have two branches that are pushing PRs to libretro/libretro-thumbnails. One branch only features renames for existing thumbnail files with improper chars. The other doesn't mess with the existing folders, and only adds new MAME thumbnails.

I really hope that I didn't miss any bad file names on the MAME thumbnails, but if I you spot any please let me know. It's been quite an undertaking to get this set together with the right resolutions and filenames. I'm hoping very soon I can say I'm "done" with MAME thumbs!

**Comment by kwyxz** [comment]
Sure thing. I focused on Neo-Geo and CPS1/CPS2 for boxarts / posters because the entire MAME library is colossal. I will take a look at your commits. Thanks!

**Comment by Kivutar** [comment]
30k files, wow!

**Comment by Kivutar** [comment]
I merge it now?

**Comment by markwkidd** [comment]
Hey @Kivutar -- yes it's fine with me to go ahead with the merge. MAME Named_Titles and Named_Snaps folders now have the complete set.

I am working on a few more flyers to add to Named_Boxarts but I can create a new PR once that is ready.

**Comment by kwyxz** [comment]
Regarding boxarts @markwkidd, I got the Neo-Geo games covered so you don't have to.

**Comment by kwyxz** [comment]
Actually, I see a handful of Neo-Geo games in your latest commits and several of them are posters, not boxarts. What's the policy on this?

**Comment by markwkidd** [comment]
As it's been explained to me, we use flyers for games and systems that don't have box art. My area of knowledge is mainly the older MAME cores and their arcade games, so I'm not really familiar with Neo Geo CD emulation that's come into MAME from MESS. Those are the games you're referring to, right?

**Comment by kwyxz** [comment]
I am referring to the Neo Geo games that are already in MAME, not through MESS. The Neo Geo was both a home system (the AES) and an arcade system (the MVS) and virtually every arcade game using the Neo Geo driver exists as a home version. As such they all have legit boxarts coming from actual boxes - contrary to most arcade games that came with flyers but no boxarts.

The Neo Geo CD is yet another compatible home system, based on the same hardware, that used CD-ROMs instead of game cartridges as a game media. 

One of the roots of this confusion I guess is that there is no clear separation from AES and MVS within RetroArch? No icon theme in every XMB for the SNK - Neo Geo hardware, for example (though there is one in some)

**Comment by markwkidd** [comment]
For what it's worth everyone, I went ahead and processed all of the remaining flyer/boxart files that I had remaining. This PR now contains every MAME thumbnail I can come up with -- it's definitely ready to be merged now from my perspective.

**Comment by twinaphex** [comment]
OK, let's do it.

**Pull request merged**
