### PR TITLE
remove outdated and unused DAT file

### PR DESCRIPTION
**Pull request by markwkidd**
I came across this datfile today which doesn't seem to belong here in the thumbnail repo. It seems to be the No-Intro datfile which was presumably used to generate the SNES libretro database initially.

### CODE REVIEW

**Comment by RobLoach** [comment]
[tgdb.pl](https://github.com/libretro/libretro-thumbnails/blob/master/tgdb.pl) used the .dat held in the folder itself to help the initial scraping. Not sure they're needed anymore.

@Kivutar?

**Comment by RobLoach** [comment]
This should be good to go. The dat is old.

**Comment by markwkidd** [comment]
Thanks @RobLoach. Maybe a more decisive PR title will help, so I'm trying a new one.

**Comment by Kivutar** [comment]
tgdb.pl is not usefull anymore, now that people are adding image manually, they choose better than my naive script :)

**Pull request merged**
