### PR TITLE
Add Pokemon Mini (Named_Boxarts)

### PR DESCRIPTION
**Pull request by lasers**

### CODE REVIEW

**Comment by sergiobenrocha2** [comment]
Do you have 512 px size of these box arts?

**Comment by lasers** [comment]
All images are converted 512x png.

**Comment by lasers** [comment]
Ha ha. I thought afterward... Wait a minutes! No, I don't!

**Comment by sergiobenrocha2** [comment]
take a look:

https://github.com/libretro/libretro-thumbnails/issues/3

**Comment by sergiobenrocha2** [comment]
Well, they are obscure games, I guess it can be 256 px

**Comment by lasers** [comment]
I think so too. The original sizes (in jpg).
```
200x203
240x238
260x259
260x259
260x259
260x259
280x280
384x384
500x499
```

**Comment by lasers** [comment]
If you cloned this repository, can I get a latest "git ls-tree" from you? Thanks in advance.

**Pull request merged**
