### PR TITLE
MAME thumbnail sets

### PR DESCRIPTION
**Pull request by markwkidd**
Updates below ....

(I used local batch processing and scripting to size and name the thumbnails according to the standard used for the FBA playlist and FBA thumbnails.)

### CODE REVIEW

**Comment by RobLoach** [comment]
Nicely done on this. Could this be applied to the latest `MAME` set?

**Comment by markwkidd** [comment]
Yes, this process will generate a thumbnail set for any given MAME ROM set or ones based on MAME like FBA.

Even though the bulk operations are scripted, this does take some manual intervention and a day or to of processing and downloading I should say 

I'm very glad to whip up a Thumbail set for the latest  MAME to send like this via google drive or  I'm also glad to clean up my Windows scripts and instructions  on how to do it and post that here too.

What's most useful for you all?

**Comment by RobLoach** [comment]
Either one you find easiest :wink: .

**Comment by markwkidd** [comment]
I'm going to do both, actually.

I'm starting with exploring the practicality of an 'omnibus' approach to MAME thumbnails. There are plenty of titles that got changed between MAME 2000/0.78 and MAME 2014/0.159, but the game titles were overall pretty stable. In other words, it may not be that hard to support all of the stable libretro MAME cores without introducing more than 5-8% extra filesize over just Thumbnails for the most recent.

Once I have a handle on this I'll post here again.

**Comment by markwkidd** [comment]
I have spent much more time wrapping my head around the MAME thumbnail question than I anticipated, but it has had it's rewards I suppose. :)

I'd like to advocate for either of two approaches.

Suggestion A: Only offer a thumbnail pack that incorporates all of the name variations for the frozen MAME cores (2000, 2003, 2010, 2014). This is less than 7% larger in file size than MAME 2014 alone.

Suggestion B: Offer the aforementioned thumbnails -- maybe call them RetroMAME thumbnails, or the like. Also offer a thumbnail set that loosely keeps up with MAME-git.

Both suggestions would allow users to contribute missing images. Suggestion A by itself would honestly support the vast majority of MAME-git titles anyway.

I think after sorting through tens of thousands of scraped MAME imagery that it might be best to separate the stable 'Retro' core thumbnails from the actively evolving -- albeit slowly -- name database of the current MAME.

**Comment by markwkidd** [comment]
All that being said, I have prepared a new set of Named_Boxarts, Named_Snaps, and Named_Titles. This is the set that would be part of either of my suggestions, with that incorporate every flyer, snapshot, and title screen supported by the arcadeitalia.net database for MAME 0.37b5, 0.78, 0.139, and 0.159. arcadeitalia uses the same Progetto-SNAPS dat file for reference as does the libretro cores.

This should be a very solid starting point for whatever folks want to do with MAME thumbnails from here onward:

"RetroMAME Onmnibus Thumbnails"
* Named_Snaps: https://mega.nz/#!109CWDBK
* Named_Titles: https://mega.nz/#!thNGyCjb

edit: I discovered a minor issue with the Boxarts set. I'm reuploading but it may be a few hours before I have a link.

**Comment by dankcushions** [comment]
nice! I don't know the capabilities/limitations of retroarch here but I have some experience in trying to sort out my local snaps. I found that there's a gulf in quality between the ones available. some findings here: https://github.com/sselph/scraper/issues/96

so I recommend:
- png format (which is **potentially** pixel perfect with no visible compression)
- native resolution/no resizing (even though these are "thumbnails", even a full size arcade snap will be 320x240 or similar - let the renderer resize if needed)
- no visible compression (in my prev link you can see what happens when PNG format is misused, so just having PNG images isn't a gurauntee that they are good)

**Comment by markwkidd** [comment]
I'm somewhat insane about image scaling myself, I feel I'm in good company. I worked exclusively with arcadeitalia image sets, which I think have not been improperly manipulated as reported in your link.

My approach to scaling: I separated each of the thumbnail sets into about six groups based on their original resolution. My goal was to have each one looking its best at 512px wide (RetroArch standard). For example this 'custom' approach meant that images that were 511px wide (or 255px wide, etc) got resampled to 512px rather than scaled and sharpened like images that started at 560px wide.

All that said, I'm now paranoid that even with my close attention I could have overlooked a quality issue. Do you know what game that is being used at your link to compare image quality? Maybe I could find images from the same game in my set for comparison.

**Comment by dankcushions** [comment]
haha, glad i'm not the only one :)

> My approach to scaling: I separated each of the thumbnail sets into about six groups based on their original resolution. My goal was to have each one looking its best at 512px wide (RetroArch standard). For example this 'custom' approach meant that images that were 511px wide (or 255px wide, etc) got resampled to 512px rather than scaled and sharpened like images that started at 560px wide.

does retroarch have to have 512px images? it doesn't do any scaling if they're lower/higher? only for me it's much better to have our images at native resolution (which is generally smaller than 512 wide), and let the UI (ie, GL) do the scaling in realtime (which should be better quality). this future proofs it for any later interfaces.

with pngs they're quite able to store full quality actual resolution screenshots for older games, at only ~10KB, but you start scaling them and they quickly look ugly IMO, and probably larger file size. i show some examples of this in that linked issue.

the game in my examples was caveman ninja (cninja.zip). i noticed that my browser applied some smoothing to the images so best to download them and look in an image viewer, to see the difference

**Comment by markwkidd** [comment]
> only for me it's much better to have our images at native resolution (which is generally smaller than 512 wide), and let the UI (ie, GL) do the scaling in realtime (which should be better quality).

This is the difference in our philosophies I think. I believe that pre-scaling images to the RA standard with a human eye involved will result in better results due to being able to adjust the scaling and sharpening appropriately depending on the source image. In other words, GL probably doesn't understand that a 240px thumbnail needs to be scaled and sharpened to 512px in a different way than a 1024px thumbnail.

That said, it's easy for me to prepare a similar pack that only scale down thumbnails larger than 512px wide and leave the rest in their original resolution. (my understanding of RA policy is to not accept thumbnails larger than that width)

I'm attaching the arcadeitalia source version 'my' Caveman Ninja thumbnail as well as the renamed and scaled version. 

Source: cninja

Renamed and scaled: caveman ninja world revision 3

**Comment by Kivutar** [comment]
We set that 256/512 limit because we store the images on a git repository, and cloning it becomes very difficult as it grows.

**Comment by dankcushions** [comment]
can you effectively adjust the sharpening on a low resolution image?

i guess that cninja snap scales fine as the source is 256, so it's a simply 2x scale, however it does double the file size with no visual gain (as presumably GL would scale exactly the same, IF that's how RA does it). interestingly, the snap pack i sourced from has a cninja image that is just 16KB vs your 29KB original. the image maybe is less busy.

however i think it gets tricky with images that can't scale so simply (ie, horiz resolution is not a factor of 512). at that point you can't eliminate scaling artifacts unless you use a massively higher resolution PNG or have the image compressed in some way. at that point i would leave it to GL.

eg, what is your thumbnail and original for SF2 (384 across)?

**Comment by dankcushions** [comment]
@Kivutar so it's just a size concern? in that case is it best to just keep sub-512 images at their original resolution? does RA resize them nicely within the GUI?

**Comment by Kivutar** [comment]
It's just size concern. If you have sub 256 or sub 512 images then keep it as is. RA will resize them with a bilinear filter.

**Comment by markwkidd** [comment]
Cool. Let me rework these and repost.

**Comment by markwkidd** [comment]
Hey @dankcushions I know we're going to original resolution thumbnails for < 512px wide, but I would be interested in hearing your thoughts on the scaling that my approach used on the 384px wide SF2 thumbnail like you mentioned. For academic reasons.

Source: sf2

Renamed and scaled: street fighter ii - the world warrior world 910522

**Comment by dankcushions** [comment]
@markwkidd for me they look good (obviously altered when you zoom in, but i doubt this is apparent in real use) but that comes at a 10x filesize cost.

**Comment by markwkidd** [comment]
I've made the change, which saves 

**'RetroMAME Omnibus Thumbnails' (MAME 2000/2003/2010/2014 name variations)**
* Named_Boxarts: https://mega.nz/#!0hMjQBzD!b2xztJUmz0KxTRvs8ZLR-BhjdVOWMe0TeM4OzjpKQtM 
* Named_Snaps (v2) https://mega.nz/#!YxkAyCqK!43wNbAzCcSd3dTOYdGk6imKagXWLvjCoHLH9KfmJi58
* Named_Titles (v2) https://mega.nz/#!FxkikLxJ!n32J6V8UIZtyVw93ypytEpuDo_SLADEiukgGMitQzuI

**Comment by markwkidd** [comment]
@RobLoach sorry to bug you. What do you think of this latest thumbnail set?

**Comment by RobLoach** [comment]
Nicely done,  I haven't tried having MAME in RetroArch yet, but this would be a good way to test it out.

> Source: sf2.png Renamed and scaled: Street Fighter II - The World Warrior (World 910522).png

RetroArch will scale the images just fine. This wasn't made in all the sources, right?

**Comment by markwkidd** [comment]
Yeah @RobLoach, in the latest thumbnail sets I linked in the post above, the thumbnails that started as less than 512px wide remain at their original resolution for RetroArch to scale up. Thumbnails that were larger than 512px wide are scaled down to 512. 

(Please ignore the sf2 snapshot scaling test post, that discussion was purely for academic purposes)

**Comment by markwkidd** [comment]
I'm going to close this pull request. Partly it's because I have learned since July that pull requests without code changes are discouraged in these repositories. Partly because I don't think the long planning conversation in this thread is helping anyone find the good stuff here at the end.

I'm moving to an issue, as it should have been originally: https://github.com/libretro/libretro-thumbnails/issues/137

**Pull request closed without merging**
