### PR TITLE
Update Cave Story

### PR DESCRIPTION
**Pull request by RobLoach**
This is the https://github.com/libretro/libretro-thumbnails/pull/169# PR from @lasers without the additional directory.

### CODE REVIEW

**Comment by lasers** [comment]
Remove additional 1f0dad3, fa851c4 ?

**Comment by RobLoach** [comment]
> Remove additional 1f0dad3, fa851c4 ? 

No, that's okay. One is the snap of En, one is snap of Ja. 

> Do I need to make rdb too?

The RDBs in https://github.com/libretro/libretro-database could do with an update.

**Comment by lasers** [comment]
bc98a59, 4663054 replaces 1f0dad3, fa851c4

**Comment by lasers** [comment]
I'll push out the former pics with correct sizes soon. Too much rock filler in the updated version.

**Comment by lasers** [comment]
@RobLoach Sorry. I destroyed my (web) master. Resize 1f0dad3, fa851c4 to 512px and get rid of the updates... then merge. 👍

**Comment by RobLoach** [comment]
Squashed the commits. Those commits were already in there :wink:

**Comment by lasers** [comment]
I wanted to put out the other images (less rock filler) for thumbnails. 😜

**Pull request merged**
