### PR TITLE
Delete all .txt files

### PR DESCRIPTION
**Pull request by RobLoach**
It is possible to see what thumbs are missing through https://github.com/robloach/libretro-thumbnails-check .

### CODE REVIEW

**Comment by kwyxz** [comment]
Aaargh :( the txt files were very useful to me to track the missing boxarts (I am currently working on updating the SFC/SNES library with localized boxarts - Japanese / US / Europe)

I tried using libretro-thumbnails-check and it fails to build for me:

```
npm install
npm WARN package.json libretro-thumbnails-check@0.0.1 No repository field.
npm ERR! git clone git@github.com:github:robloach/datfile Cloning into bare repository '/home/kwyxz/.npm/_git-remotes/git-github-com-github-robloach-datfile-f931c696'...
npm ERR! git clone git@github.com:github:robloach/datfile fatal: remote error: 
npm ERR! git clone git@github.com:github:robloach/datfile    is not a valid repository name
npm ERR! git clone git@github.com:github:robloach/datfile   Email support@github.com for help
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'datfile' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'libretro-thumbnails-check'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.8.0-2-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /usr/local/src/libretro-thumbnails-check
npm ERR! node -v v4.6.1
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/src/libretro-thumbnails-check/npm-debug.log
npm ERR! not ok code 0
Makefile:5: recipe for target 'node_modules' failed
make: *** [node_modules] Error 1
```

But even if it was working I am afraid it will make my current efforts considerably longer. Can we please reconsider this deletion?

**Comment by RobLoach** [comment]
The reports are already built in the [`out` directory](https://github.com/RobLoach/libretro-thumbnails-check/tree/master/out). They old .txt files may be rather inaccurate by now, as No-Intro has updated a bunch of names.

If you would still like them, you could see:
https://patch-diff.githubusercontent.com/raw/libretro/libretro-thumbnails/pull/171.diff

We could revert this PR too, the txt files arn't hurting anything. I just saw a bunch of them appear [in the Orphan file reports](https://github.com/RobLoach/libretro-thumbnails-check/tree/master/out).

**Comment by kwyxz** [comment]
If I can get the thumbnails check tool to work, I'll figure out a way to generate similar files that will help me keep track of my progress without having to revert. If I can't make it work I'll let you guys know :) thanks!

**Comment by RobLoach** [comment]
> If I can get the thumbnails check tool to work, I'll figure out a way to generate similar files that will help me keep track of my progress without having to revert.

It's not really that special :wink:  Just reports all the missing/haves to the out directory:
https://github.com/RobLoach/libretro-thumbnails-check/tree/master/out

**Comment by kwyxz** [comment]
Alright, now that I've got @RobLoach's tool working, I think I will easily find a way to work without the txt files in the git repo. I'm relieved! :D

**Pull request merged**
