### PR TITLE
Added new PSP Boxart

### PR DESCRIPTION
**Pull request by JoseBarakat**
Added 
Ben 10 - Alien Force (USA) (En,Fr,De,Es,It) (v1.01).png
Dimensions: 512 × 882
File size: 757,6 kB

### CODE REVIEW

**Comment by JoseBarakat** [comment]
Hi @Kivutar. I started learning GitHub and decided to start contributing to libretro-thumbnails.
If I'm not following any guideline, please let me know.

**Comment by Axiphel** [comment]
The file path is incorrect. You can't upload with the browser website because of a bug with github that doesn't like spaces. Uploading with the website creates a file path like Sony%20-%20PlayStation%20Portable

**Comment by JoseBarakat** [comment]
@Axiphel Ok. So, do I have to clone the entire repository in my local disk? I wanted to, first, upload to this subdirectory (libretro/libretro-thumbnails/Sony - PlayStation Portable/Named_Boxarts/) but didn't know how to clone just one subdirectory.

Tried this without succes:

``` bash
~$ mkdir libretro-thumbnails
~$ cd libretro-thumbnails
~/libretro-thumbnails$ git init
  Initialized empty Git repository in /home/jose/libretro-thumbnails/.git/
~/libretro-thumbnails$ git remote add origin https://github.com/libretro/libretro-thumbnails.git
~/libretro-thumbnails$ git config core.sparsecheckout true
~/libretro-thumbnails$ echo "Sony - PlayStation Portable/Named_Boxarts/" >> .git/info/sparse-checkout
~/libretro-thumbnails$ git pull https://github.com/libretro/libretro-thumbnails.git
remote: Counting objects: 96589, done.
```

**Comment by twinaphex** [comment]
Ideally Github fixes this bug, somebody already pointed this out to them but it seems they haven't been able to fix it yet or they just ignored it.

**Comment by JoseBarakat** [comment]
Thanks @Axiphel and @twinaphex . I'll wait for that fix. I'm looking forward to contribute to this project.

**Comment by JoseBarakat** [comment]
They don't seem to be interested to fix that issue, specially because URL's can't contain spaces (maybe that's the reason). Should I report this to support@github.com, or maybe we have to change spaces for its encoding character "%20" or undercores "_" ? Thank you.

**Comment by twinaphex** [comment]
@Alcaro did anybody report back to you from Github when you filed that bug, or have there been any status updates?

**Comment by Alcaro** [comment]
I got one reply, which I reposted in another issue. Nothing since then.

**Comment by JoseBarakat** [comment]
Just sent an e-mail to GH support team.

**Comment by JoseBarakat** [comment]
I just received this from Stacey Burns - GitHub Staff:

> 
> Hey Jose,
> 
> Sorry for the trouble.
> 
> This is a bug that we are currently working on getting a fix out for. I can't promise an ETA but as soon as we have some news, we'll be in touch!
> 
> Cheers
> Stacey

So, we'll just have to wait.

**Pull request closed without merging**
