### PR TITLE
Near complete SNES set of boxarts

### PR DESCRIPTION
**Pull request by kwyxz**
With this final push, we are close to 100% completion on Super NES / Super Famicom boxarts. I have tried, for every rom in the No-Intro DAT, to provide the localized boxart (either Euro / US / Japanese, and sometimes different Euro covers when applicable, same with Rev 1 / Rev 2 when possible)

### CODE REVIEW

**Comment by twinaphex** [comment]
Some of this boxart is low-quality though. We will likely have to do lots of cleaning up after merging this with higher-quality versions.

**Comment by twinaphex** [comment]
Do me a favor, and check out if the boxart you're replacing is not of higher quality than the ones you're replacing it with. If you can guarantee you're only replacing lower-quality boxart, then we can merge this.

**Comment by kwyxz** [comment]
Yeah, sadly some of the boxarts were impossible to find in great quality :/ but I'm positive I have been careful about not replacing good quality boxarts with lower quality ones.

**Comment by twinaphex** [comment]
Well there are merge conflicts anyways, so you'll have to check it manually regardless.

**Comment by kwyxz** [comment]
Fixed the conflicts, sorry about this.

**Pull request merged**
