### PR TITLE
Add PSX boxart

### PR DESCRIPTION
**Pull request by budtske**
Also fixing 2 bad quality jaguar boxart files

### CODE REVIEW

**Comment by RobLoach** [comment]
There are a few files that are in the rot directory. May want to move them to the Playstation/Boxart directgory.

**Comment by xTMODx** [comment]
I wouldnt accept them, they are all edited and not accurate please check this http://psxdatacenter.com/ and see how they should look like they are made to look similar to each other

**Comment by twinaphex** [comment]
We don't want non-original PSX boxart yeah. Kill that with fire please. The Jaguar boxart seems mostly okay.

**Comment by budtske** [comment]
Was unaware, apologies

**Comment by twinaphex** [comment]
You can resubmit the Jaguar boxart however.

**Comment by budtske** [comment]
I will after cleaning up my repository.
Is there a wiki with guidelines I can check to prevent further mistakes? (apart from only original boxart)

The reason I was mistaking this as original artwork is because I have some launch items that are this size.  Aperantly they only did this in the first year. see here: http://www.gamesradar.com/an-extremely-interesting-history-of-game-packaging/4/

**Pull request closed without merging**
