### PR TITLE
Adding More PSX Screenshots

### PR DESCRIPTION
**Pull request by cityeyes**
Adding a few original PSX Screenshots

### CODE REVIEW

**Comment by Kivutar** [comment]
I merge this for now but I have one question, are those screenshot at the native resolution?

**Comment by davmanypsp** [comment]
Can somebody confirm the resolution for the Sony Playstation snaps? I thought it was 512px, and I've been taking some but didn't upload them yet.

**Comment by Kivutar** [comment]
It is game dependant, if you launch the game in retroarch, and use the screenshot feature, you should get the right resolution.

**Comment by davmanypsp** [comment]
Ok, thanks.

**Comment by cityeyes** [comment]
Kivutar, regardless of what settings I screenshot them in, they're coming out as 1920x1440 straight out of retroarch, which I think matches the 4:3 ratio when applied to my current monitor resolution.

I sized them down to 512 because the existing PSX screenshots were that res and because 512 is pretty much the highest typical resolution that PSX was rendered at.

I did have GPU upscaling on when making the screenshots,but I didn't think it'd affect much considering I have to size them down in post anyway, let me know if you'd like me to re-do them eventually.

**Comment by Kivutar** [comment]
Try to disable GPU screenshots maybe?

**Comment by cityeyes** [comment]
Ah, that did it. Forgot I'd even turned that setting on. Coming out in 320x240, at least for Brave Fencer Musashi,

**Pull request merged**
