### PR TITLE
Wonderswan / Jaguar / Saturn / Neo Geo AES/ others boxarts

### PR DESCRIPTION
**Pull request by kwyxz**
Hello,
Here is a near complete set of boxarts for Wonderswan / Wonderswan Color / Atari Jaguar
As well as a bunch of boxarts for Saturn and a few other things (Neo Geo for Final Burn)
I hope I did things properly and these can be merged into the project :)
Thanks and keep up the good work!

### CODE REVIEW

**Comment by kwyxz** [comment]
I noticed that more recent versions of MAME have changed some naming (capital letters where there were small letters), for example : 

Fatal Fury - King of Fighters _ Garou Densetsu - shukumei no tatakai (NGM-033)(NGH-033).png
is now
Fatal Fury - King of Fighters / Garou Densetsu - Shukumei no Tatakai (NGM-033 ~ NGH-033)

Policy is to get rid of the ~ afaik but caps are a real issue for users of a case sensitive filesystem
I guess my next push will be an attempt to get this straight

**Comment by kwyxz** [comment]
I have noticed more issues with special characters. Is there any spec or guideline somewhere? 

Most of them are replaced with "_" but it's not the case for "~" for example : see in my previous comment where (NGM-033 ~ NGH-033) seems to become (NGM-033)(NGH-033)

Similar issue with a "," in a game name

For the time being I'll replace all of them by "_" and not perform any additional change, for consistency with the MAME naming, until some rule is offered.

**Comment by markwkidd** [comment]
Hi @kwyxz - I'm replying to your message on my MAME thumbnails PR as well.

The naming policy I have been using with my playlist and thumbnail scripts comes from a post by @Kivutar which I have been unable to find. However, I can paste the list of characters that are supposed to be replaced by underscores according to my records:
& \ / ? : < > : * |

It seems important to have a standard policy because the thumb files need to have the same name that the playlist generator assigns to the ROMs in order for the thumbs to appear correctly. I hope that this list of characters helps you, or that a dev hops into this PR and can be more useful than I am about the exact current policy.

**Comment by kwyxz** [comment]
I've been using a subset of this renaming pattern:

`tr '/' '_' | tr '~' '_' | tr ',' '_' | tr '?' '_' | tr '&' '_'`

Looks like I could add the other ones. Thanks for the pointer!

**Comment by markwkidd** [comment]
The only thing I see on your list that jumps out at me is the ~ character. As far as I know it isn't RetroArch convention to rename that character.

**Comment by kwyxz** [comment]
You sure? When I forked the thumbnails archive the `~` were all absent [as mentioned above](https://github.com/libretro/libretro-thumbnails/pull/141#issuecomment-258344503). 

But it could also be a new MAME convention... I'm using the latest MAME to get the names. I guess I should compare with an older version.

**Comment by markwkidd** [comment]
My understanding of the libretro MAME cores is that they use the Progetto-SNAPS XML DAT files as their reference. For any given MAME version, the names from the DATs and the MAME executable should be the same though, right? 

At any rate, I've been referring to Progetto-SNAPS (for 0.159, 0.139, 0.78, and 0.37b5) if that explains anything. http://www.progettosnaps.net/dats/

**Comment by kwyxz** [comment]
Ha, thanks, I did not know about the Progetto-SNAPS. I will use them for naming from now.

**Comment by kwyxz** [comment]
I checked out the Progetto-SNAPS and they are using basically the DATs that come with Mame.
Here's an example of a possibly problematic file name:

`3 Count Bout / Fire Suplex (NGM-043 ~ NGH-043)`

I have replaced the `~` with `_` in my snaps but according to the list of problematic characters I found [in this post](https://github.com/libretro/libretro-thumbnails/issues/19) it may not be necessary. @Kivutar do you have an opinion on this? 

Thanks!

**Comment by markwkidd** [comment]
It has taken a while, but there is now an official file naming policy, which just got merged into the README for this repo: https://github.com/libretro/libretro-thumbnails/blob/master/README.md

In short, RetroArch is going to mirror the No-Intro filename standard by replacing these characters with an underscore: &*/:`<>?\\|

This slightly different than what we were using above. It does prohibit the colon (:) and the backtick (`) character, but does not prohibit the semicolon (;). I hope that certainty about the list of characters will help you not have to worry about technicalities so you can focus on helping add thumbnail images! :)

**Comment by kwyxz** [comment]
Thanks, this is great! 

I think I am going to split my Neo Geo AES covers into a dedicated directory - some UI themes have one, some others haven't - so that we can have both the home console boxarts and the posters from the arcade versions with your commit.

**Comment by Kivutar** [comment]
So should we merge this PR?

**Comment by twinaphex** [comment]
I'll take a chance by merging this.

**Comment by kwyxz** [comment]
Thanks @Kivutar and @twinaphex for the merge!

@markwkidd I use the latest MAME for naming conventions as IMHO it is the most up-to-date and the most recognized, though I understand your concern regarding the MAME2000 and MAME2003 cores. I will stay clear of MAME and let you take care of it as you seem more comfortable with them :)

Regarding the use of posters VS boxarts I am still planning on creating a specific SNK - NEO GEO directory for the AES home console with the boxarts, then posters can be used for the arcade MVS system. It makes more sense considering how other arcade games are handled even for FB Alpha.

**Comment by kwyxz** [comment]
I also plan on working on more console boxarts, it's way easier than having to deal with MAME :D

**Pull request merged**
