### PR TITLE
Added 43/63 Watara Supervision boxarts

### PR DESCRIPTION
**Pull request by cfillak**
I pulled this set of Watara Supervision box art from this thread on hyperspin: http://www.hyperspin-fe.com/topic/11561-watara-supervision-box-2d/  . Some seem to be scans while others were created with the template designed by the user Dasman of hyperspin forums. Alot of Supervision games came packaged in not so nice looking plastic blister packages, so these custom designs offer a huge improvement in quality and uniformity across the set. Only 43/63 ROMS are covered in this boxart set.

### CODE REVIEW

**Comment by Kivutar** [comment]
Thanks!

We prefer unmodified boxarts when possible.

But it's still better than having nothing.

**Comment by cfillak** [comment]
What's the policy for when a game doesn't really come in a box? Like a pack-in cartridge or something.

**Comment by Kivutar** [comment]
We try to find the closest thing to a box art, for example the Flyers for the Arcade games, or the photo of the package for the Sega Mark III cards.

**Comment by cfillak** [comment]
Ah, ok. That makes sense. So the priority is a real image of an artifact related to the game (box, package, cart label etc.) over reconstructions.

**Pull request merged**
